version: "2"
linters:
  default: none
  enable:
    - errorlint
    - sloglint
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - e2e
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prometheus/graphite_exporter
  exclusions:
    generated: lax
    paths:
      - e2e
      - third_party$
      - builtin$
      - examples$
