name: golangci-lint
on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "scripts/errcheck_excludes.txt"
      - ".github/workflows/golangci-lint.yml"
<<<<<<< HEAD
      - ".golangci.yml"
=======
>>>>>>> 199dc86 (Update common Prometheus files)
  pull_request:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "scripts/errcheck_excludes.txt"
      - ".github/workflows/golangci-lint.yml"
<<<<<<< HEAD
      - ".golangci.yml"
=======
>>>>>>> 199dc86 (Update common Prometheus files)

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
